### ISSUE TITLE
exceptional termination

### ISSUE THREAD

**Issue by KihongHeo** [dbousque/lymp#1]
Hi,

Recently, I came across this project and really appreciate your work. Wonderful!
I try to bind my ocaml and python programs with Lymp.
But my ocaml program exceptionally terminates without any error message  (no errors in ```python_log``` also).
What I found is that the ocaml program runs well if I remove ```Lymp.close```. 
My ocaml program uses Lymp only at the beginning and runs on the remaining part with the results computed from python modules. 

Do you have any idea and could you give some advice?

**Comment by dbousque** [comment]
Hi there,

I'm glad you appreciate the package. Could you tell me what OS you are using and what lymp version you have ? Do you close lymp as soon as you got data from python or do you close it at the end of the computation ? It would be great if you could give me a minimal crashing example I could test.

**Comment by KihongHeo** [comment]
I use Lymp 0.1.2 on Linux. Currently I try to make a minimal crashing example but it is not very easy. 
My program closes lamp after getting data from python like the following code:

```ocaml
  let py = Lymp.init ~exec:"python2" "strategy" in
  let py_module = Lymp.get_module py "harmless_unsoundness" in
  let classifier = Lymp.Pyref (Lymp.get_ref py_module "load" [Lymp.Pystr "harmless_loop_clf"]) in
  let set = Map.foldi (fun id vec set -> 
    let b = Lymp.get_bool py_module "is_harmless" [classifier; vec] in
    if b then Set.add id set else set) map Set.empty in
  Lymp.close py;
  (* other computation with the set *)
```
In the python module 
```python
def load(name):
  with open(name, 'r') as f:
    clf = pickle.load(f)
  return clf
```
```load``` reads an object from a file using ```pickle``` . 

When I find a minimal example, I will put it soon.

**Comment by dbousque** [comment]
Could you tell me what exception you have ? Is it `Fatal error: exception Lymp.Pyexception` ? If so, check `strategy/python_log` (`python_log` is in the directory from which python was launched, so `strategy` in your case). If you find no useful information there, could you please send me your complete directory structure (at least enough to test) ?

Some random ideas of what might go wrong : 
- is `python2` a valid command ?
- does `stategy/harmless_loop_clf` exist ?
- is `harmless_unsoundness.py` inside `strategy` ?

So I can test more thoroughly, what is `Map.foldi` ?

**Comment by KihongHeo** [comment]
It is strange that there is no exception raised. Also ```python_log``` is empty. 
All of the computation in the python module is successfully transformed to the ocaml module. (```python2```, ```harmless_loop_clf```, ```harmless_unsoundness.py``` are valid)

I will look into it more deeply.

**Comment by KihongHeo** [comment]
I think this problem is related with garbage collection.
When I put ```Gc.minor ()``` here and there in my ocaml program after calling ```Lymp.close```, the exceptional behavior also differs. 
If I do not close the python module, it runs correctly.

**Comment by dbousque** [comment]
Do you say that no exception is raised ? If that is the case, how do you know that something is wrong ?

I think I might know what is going on. References returned are released on the python side when the OCaml's garbage collector finalizes them. Releasing after `Lymp.close` would be invalid, so that may be what is going wrong. I will further investigate. For now, if my hypothesis is correct, putting `Gc.full_major ()` before `Lymp.close`, in a way that would garbage collect the reference would work, like that for example : 
```ocaml
let get_set py =
    let py_module = Lymp.get_module py "harmless_unsoundness" in
    let classifier = Lymp.Pyref (Lymp.get_ref py_module "load" [Lymp.Pystr "harmless_loop_clf"]) in
    let set = Map.foldi (fun id vec set -> 
        let b = Lymp.get_bool py_module "is_harmless" [classifier; vec] in
        if b then Set.add id set else set) map Set.empty in
    set

let py = Lymp.init ~exec:"python2" "strategy" in
let set = get_set py in
Gc.full_major () ;
Lymp.close py
  (* other computation with the set *)
```

A simpler solution would be to just put `Lymp.close` at the very end of your program, could you tell me if that works ?

**Comment by KihongHeo** [comment]
>Do you say that no exception is raised ? If that is the case, how do you know that something is wrong ?

Because the program terminates without printing out the final results. 

```Gc.full_major ()``` before ```Lymp.close``` works. For now, I will use this temp solution.

**Comment by dbousque** [comment]
Great, I will fix it then. Thanks for reporting the issue.

**Comment by dbousque** [comment]
The fix is available in lymp 0.1.3, I will let you know when the package is ready on opam.

**Comment by dbousque** [comment]
Hi,
lymp 0.1.3 is now available, you can get it like so for example : `opam uninstall lymp && opam update && opam install lymp`. Can you tell me if that fixes the bug ?

**Comment by KihongHeo** [comment]
Hi, 
It works very well. Thanks for your update.
