### ISSUE TITLE
Feature request for handling tuples 

### ISSUE THREAD

**Issue by pbaudin** [dbousque/lymp#2]
Hi,

I am looking for binding a Python library using a lot of kinds of tuple types for the arguments of the  functions to bind.

Lymp is using Json that serializes tuples as lists. So, it is impossible to get  back to tuples when deserializing. It sems to be the reason why `Lymp.get` returns an Ocaml  `Pylist _` value. 
Even using `Lymp.get_ref` to get a reference, it is still a reference on a python list and not on a tuple.   

I found on stackoverflow a code able to serialize/deserialize  tuples as tuples! 

So, the question is the folowing:
Using part of this code into `Lymp.py`, would it be possible for you to extend the `Lymp.pyobj` type with a `| Pytuple of pyobj list` in order to keep tuples as tuples at the Python side ?
 
source: http://stackoverflow.com/a/15721641

```code=python
import json

class MultiDimensionalArrayEncoder(json.JSONEncoder):
    def encode(self, obj):
        def hint_tuples(item):
            if isinstance(item, tuple):
                return {'__tuple__': True, 'items': item}
            if isinstance(item, list):
                return [hint_tuples(e) for e in item]
            else:
                return item
            
        return super(MultiDimensionalArrayEncoder, self).encode(hint_tuples(obj))

def hinted_tuple_hook(obj):
    if '__tuple__' in obj:
        return tuple(obj['items'])
    else:
        return obj

enc = MultiDimensionalArrayEncoder()
jsonstring =  enc.encode([1, 2, (3, 4), [5, 6, (7, 8)]])

print jsonstring
# [1, 2, {"items": [3, 4], "__tuple__": true}, [5, 6, {"items": [7, 8], "__tuple__": true}]]

print json.loads(jsonstring, object_hook=hinted_tuple_hook)
# [1, 2, (3, 4), [5, 6, (7, 8)]]
```

As you can see, the `deserialize (serialize([1, 2, (3, 4), [5, 6, (7, 8)]]))` returns the initial Python value without loosing tuples.

**Comment by dbousque** [comment]
Thanks for reporting. I implemented tuple support this afternoon, I did just like you recommended, namely adding a `Pytuple of pyobj list`, along with `get_tuple` and `attr_tuple`. It will be available in lymp 0.1.3, which I just asked to be available from `opam`. I will let you know when you will be able to upgrade using opam :)

**Comment by pbaudin** [comment]
Thank's a lot . I will wait for the next update of your Opam package.

As far I could see, you added also some functions such as `get_tuple`... They are not mentioned into the `README.md` file. 

When I tryed for `simple` example, it didn't work as it is because my installed Python version is 2.7 (It the one required by the Python library I want to bind). Perhaps you can add an Ocaml comment into the `simple.ml` where the `init` function is called.

**Comment by dbousque** [comment]
`get_tuple` and the other `get_*` functions are mentioned just under the description of `get`, I didn't want to write a description for all of them, since they work the same.

I will make it clearer in `simple.ml` that one needs to change the name of the interpreter used if it's not `python3`, thanks for your feedback, it's good to know where things need to be made a bit clearer.

**Comment by dbousque** [comment]
Hi,
lymp 0.1.3 is now available, you can get it like so for example : `opam uninstall lymp && opam update && opam install lymp`
