### ISSUE TITLE
Pybytes converted to  str,  but  str converted back to Pystr with python2

### ISSUE THREAD

**Issue by pbaudin** [dbousque/lymp#4]
In Python 2, `Pybytes` are converted to `str`.
OK, but `str` are converted back to `Pystr` (and not to `Pybytes` as it should be).

You can find below an example reproducing the problem and checking the idempotence of the two conversions (Ocaml -> Python and  Python -> Ocaml) for other types.

**File `simple.py`**
```code=python
def identity(x):
    print x
    return x
```

**File `simple.ml`**
Once fixed, the all assertions should be valid. So, all calls to `assert` can be uncommented.

```code=ocaml
open Lymp

let py = init ~exec:"python2" "."
let simple = get_module py "simple"

(* ISSUE: in Python 2, Pybytes are converted to str.
   OK, but str are converted back to Pystr (and not to Pybytes as it should be). *)
    
let () =

  let arg = Pylist [  Pytuple [ Pyint (-1) ; 
                                            Pystr "str" ; Pystr ""  ] ; 
                             Pybytes "bytes" ;  Pybytes ""  ;
                             Pynone ; 
                             Pybool true ; Pybool false  ] in
  
  let x = get simple "identity" [ arg ] in (* the returned value is KO *)
  (* assert (x = arg) ; *)
  let y = get simple "identity" [ x ] in (* to show the problem with 'x' in python_log file *)
  assert (y = x) ;
  
  let z = get_ref simple "identity" [ arg ] in
  
  let x = dereference z in (* the returned value is KO *)
  (* assert (x = arg) ; *)
  let y = get simple "identity" [ x ] in (* to show the problem with 'x' in python_log file *)
  assert (y = x) ;
  
  let x = get simple "identity" [ Pyref z ] in (* the returned value is KO *)
  (* assert (x = arg) ; *)
  let y = get simple "identity" [ x ] in (* to show the problem with 'x' in python_log file *)
  assert (y = x) ;

  Format.printf "done@.";
  close py
```

**Comment by dbousque** [comment]
Thanks for reporting again. It was actually a design choice, the assumption was that `str` returned from python are ascii strings. But you're right, It's better to return `str` as `Pybytes` and `unicode` as Pystr in python 2. I did so in lymp 0.2.2, I will go back to you once it's released. Can I use that piece of code as a test to be put in `/tests` ?

**Comment by dbousque** [comment]
lymp 0.2.2 is available, you can upgrade `lymp` if you want.
